---
- hosts: localhost
  name: Cleanup local known hosts
  vars_files:
    - secret.yml

  tasks:
    - name: Ensure SSH-ability
      command:
        cmd: pressh {{ muzak_hoster }}

- hosts: muzak
  name: Check non-root user
  become: false

  tasks:
    - name: Register non-root user
      set_fact:
        nonroot_user: '{{ ansible_user_id }}'

- hosts: muzak
  name: Provision muzak
  become: true

  vars:
    caddy_version: 2.7.5
    caddyfile: /etc/caddy/Caddyfile
    cert_files:
      - crt
      - json
      - key
    cert_valid: '{{ saved_cert_valid | default(true) | bool }}'
    data_folder: /mnt/navidrome
    cert_path: /caddy/.local/share/caddy/certificates/acme{{ maybe_staging}}-v02.api.letsencrypt.org-directory/{{ muzak_hoster }}
    gcsfuse_version: 1.2.0
    maybe_staging: '{{ use_staging | default(false) | bool | ternary("-staging", "") }}'
    music_folder: /mnt/music
    navidrome_config: '{{ navidrome_folder }}/navidrome.toml'
    navidrome_folder: /mnt/navidrome
    navidrome_version: 0.49.3
    services_dir: /etc/systemd/system

  vars_files:
    - secret.yml

  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name:
          - fuse3
          - less
          - unattended-upgrades
        update_cache: true

    - name: Install gcsfuse
      ansible.builtin.apt:
        deb: https://github.com/GoogleCloudPlatform/gcsfuse/releases/download/v{{ gcsfuse_version }}/gcsfuse_{{ gcsfuse_version }}_amd64.deb

    - name: Update packages
      ansible.builtin.apt:
        name: '*'
        state: latest
        update_cache: true
      async: 600
      poll: 0
      register: apt_update

    - name: Enable unattended upgrades
      ansible.builtin.copy:
        src: unattended-upgrades.conf
        dest: /etc/apt/apt.conf.d/50unattended-upgrades

    - name: Check if gcsfuse is running
      ansible.builtin.command:
        cmd: systemctl is-active gcsfuse
      register: gcsfuse_status
      failed_when: gcsfuse_status.rc not in [0, 3]

    - name: Ensure music folder
      ansible.builtin.file:
        path: '{{ music_folder }}'
        state: directory
        owner: '{{ nonroot_user }}'
        group: '{{ nonroot_user }}'
      # Fails with `There was an issue creating <dir> as requested: [Errno 17] File exists: b''<dir>'''`
      # if gcsfuse is running.
      when: gcsfuse_status.rc > 0

    # Allows having the same users across different instances.
    - name: Mount attached disk
      ansible.builtin.mount:
        path: '{{ navidrome_folder }}'
        src: /dev/disk/by-id/google-navidrome
        state: mounted
        fstype: ext4

    - name: Ensure correct permissions for navidrome
      file:
        path: '{{ navidrome_folder }}'
        owner: '{{ nonroot_user }}'
        group: '{{ nonroot_user }}'
        recurse: true

    - name: Template gcsfuse service
      ansible.builtin.template:
        src: service.j2
        dest: '{{ services_dir }}/gcsfuse.service'
      vars:
        description: A user-space file system for interacting with Google Cloud Storage
        exec: '/usr/bin/gcsfuse --foreground --implicit-dirs {{ bucket }} {{ music_folder }}'
        service_user: '{{ nonroot_user }}'

    - name: Start gcsfuse service
      ansible.builtin.systemd:
        name: gcsfuse
        state: started
        daemon_reload: true

    - name: Download Navidrome
      ansible.builtin.unarchive:
        src: https://github.com/navidrome/navidrome/releases/download/v{{ navidrome_version }}/navidrome_{{ navidrome_version }}_Linux_x86_64.tar.gz
        dest: /usr/local/bin
        remote_src: true
        include: navidrome

    - name: Template Navidrome service
      ansible.builtin.template:
        src: service.j2
        dest: '{{ services_dir}}/navidrome.service'
      vars:
        description: Modern Music Server and Streamer compatible with Subsonic/Airsonic
        exec: /usr/local/bin/navidrome --datafolder {{ data_folder }} --musicfolder {{ music_folder }}
        service_user: '{{ nonroot_user }}'

    - name: Template Navidrome config
      ansible.builtin.template:
        src: navidrome.toml
        dest: '{{ navidrome_config }}'
        owner: '{{ nonroot_user }}'
        group: '{{ nonroot_user }}'

    - name: Start Navidrome service
      ansible.builtin.systemd:
        name: navidrome
        state: started
        daemon_reload: true

    - name: Download Caddy
      ansible.builtin.unarchive:
        src: https://github.com/caddyserver/caddy/releases/download/v{{ caddy_version }}/caddy_{{ caddy_version }}_linux_amd64.tar.gz
        dest: /usr/local/bin
        remote_src: true
        include: caddy

    - name: Ensure Caddyfile dir
      file:
        path: '{{ caddyfile | dirname }}'
        state: directory

    - name: Write Caddyfile
      template:
        src: Caddyfile
        dest: '{{ caddyfile }}'

    - name: Template Caddy service
      template:
        src: service.j2
        dest: /etc/systemd/system/caddy.service
      vars:
        description: Fast, multi-platform web server with automatic HTTPS
        exec: /usr/local/bin/caddy run --config {{ caddyfile }}
        env:
          - HOME: /caddy

    - name: Ensure cert directory
      ansible.builtin.file:
        path: '{{ cert_path }}'
        state: directory
      when: cert_valid

    - name: Read cert files
      ansible.builtin.slurp:
        path: certs/cert.{{ item }}.sops
      delegate_to: localhost
      register: certs
      loop: '{{ cert_files }}'
      become: false
      when: cert_valid

    - name: Upload cert files
      ansible.builtin.copy:
        content: '{{ item.content | b64decode | community.sops.decrypt(output_type="binary", rstrip=false) }}'
        dest: '{{ cert_path }}/{{ muzak_hoster }}.{{ item.item }}'
      loop: '{{ certs.results }}'
      when: cert_valid
      no_log: true

    - name: Start Caddy service
      systemd:
        name: caddy
        state: started
        daemon_reload: true
        enabled: true

    - name: Pause 20 seconds for fetching certificates
      ansible.builtin.pause:
        seconds: 20
      when: not cert_valid

    - name: Fetch certificates
      ansible.builtin.fetch:
        src: '{{ cert_path }}/{{ muzak_hoster }}.{{ item }}'
        dest: certs/cert.{{ item }}
        flat: yes
      loop: '{{ cert_files }}'
      when: not cert_valid

    - name: Check apt update status
      async_status:
        jid: '{{ apt_update.ansible_job_id }}'
      register: update_result
      until: update_result.finished
      retries: 60
      delay: 5

    - name: Check if restart is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot
      ansible.builtin.reboot:
      when: reboot_required.stat.exists

- hosts: localhost
  vars:
    cert_files:
      - crt
      - json
      - key
    cert_valid: '{{ saved_cert_valid | default(true) | bool }}'

  vars_files:
    - secret.yml

  tasks:
    - name: Encrypt cert files
      community.sops.sops_encrypt:
        age: '{{ age_public_key }}'
        path: certs/cert.{{ item }}.sops
        content_text: "{{ lookup('ansible.builtin.file', 'certs/cert.{{ item }}', rstrip=false) }}"
      loop: '{{ cert_files }}'
      when: not cert_valid

    - name: Delete cert files
      ansible.builtin.file:
        path: certs/cert.{{ item }}
        state: absent
      loop: '{{ cert_files }}'
      when: not cert_valid

    - name: Check for cert changes
      ansible.builtin.command:
        cmd: git status -s
      register: git_status
      when: not cert_valid

    - name: Check if there's a need for a new commit
      set_fact:
        needs_commit: '{{ git_status.stdout.strip() | length > 0 }}'
      when: not cert_valid

    - name: Git add new cert files
      ansible.builtin.command:
        cmd: git add certs/cert.{{ item }}.sops
      with_items: '{{ cert_files }}'
      when: not cert_valid and needs_commit

    - name: Commit new cert files
      ansible.builtin.command:
        cmd: git commit -m 'add new certs'
      when: not cert_valid and needs_commit

    - name: Push commit cert files
      ansible.builtin.command:
        cmd: git push
      when: not cert_valid and needs_commit
...
